[package]
name = "instru"
version = "0.0.0"
description = "Interactively play sine waves at different pitches in terminals"
license = "0BSD"
edition = "2024"

[dependencies]
clap = { version = "4.6.6", features = ["derive", "wrap_help", "unicode"] }
crossterm = { version = "0.29.0", default-features = false, features = ["windows", "events", "derive-more"]}
web-audio-api = { version = "1.2.0", default-features = false, features = ["cpal"] }
