name: Setup Toolchain

runs:
  using: 'composite'
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
        cache-all-crates: "true"
        
    - run: echo "/root/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Install Dependencies
      run: sudo apt install libasound2-dev
      shell: bash